select *
from venues
where name like '%searchQuery%';


I AM WORKING ON THE SORT FEATURE FOR USER.STYPE IN THE DROPDOWN TO EACH MAPPED VENUE TO SORT. 

NEXT: USING THE INPUT VALUE TO FILTER THROUGH THE VENUES 